-- RB20 v2.0 / Contracts / Convenience Views (v1)
-- 目的：避免在 H/E/F 等集合表中重复存储 63 列宽字段；画像需要宽字段时，统一从 rb20_v2_5.source_members 取（不回读 public 源表）。

DROP VIEW IF EXISTS rb20_v2_5.h_members_wide;
CREATE VIEW rb20_v2_5.h_members_wide AS
SELECT
  hm.run_id,
  hm.contract_version,
  sm.shard_id,
  hm.ip_long,
  hm.block_id_final,

  sm.ip_address,
  sm."IP归属国家",
  sm."IP归属运营商",
  sm."过滤前上报次数",
  sm."上报次数",
  sm."过滤前设备数量",
  sm."设备数量",
  sm."应用数量",
  sm."活跃天数",
  sm."安卓ID数量",
  sm."OAID数量",
  sm."谷歌ID数量",
  sm."启动ID数量",
  sm."型号数量",
  sm."制造商数量",
  sm."深夜上报次数",
  sm."工作时上报次数",
  sm."工作日上报次数",
  sm."周末上报次数",
  sm."以太网接口上报次数",
  sm."代理上报次数",
  sm."Root设备上报次数",
  sm."ADB调试上报次数",
  sm."充电状态上报次数",
  sm."单设备最大上报次数",
  sm."DAA业务上报次数",
  sm."DNA业务上报次数",
  sm."WiFi可比上报次数",
  sm."SSID去重数",
  sm."BSSID去重数",
  sm."网关存在上报次数",
  sm."平均每设备上报次数",
  sm."周活跃天数比例",
  sm."深夜活动比例",
  sm."工作日周末平均比例",
  sm."平均每设备重启次数",
  sm."平均每设备应用数",
  sm."DAA DNA业务比例",
  sm."上报应用比例",
  sm."低安卓API设备比例",
  sm."WiFi设备数量",
  sm."WiFi设备比例",
  sm."移动网络设备数量",
  sm."移动网络设备比例",
  sm."VPN设备数量",
  sm."VPN设备比例",
  sm."空网络状态设备数量",
  sm."空网络状态设备比例",
  sm."异常网络设备数量",
  sm."异常网络设备比例",
  sm."有线网络设备数量",
  sm."有线网络设备比例",
  sm."SIM不可用比例",
  sm."无效总流量设备比例",
  sm."零移动流量设备比例",
  sm."制造商分布风险状态",
  sm."SDK版本分布异常分数",
  sm."开始日期",
  sm."结束日期",
  sm."创建时间",
  sm."活跃日期列表",
  sm."IP稳定性",

  sm.is_abnormal,
  sm.is_valid,
  sm.atom27_id,
  sm.bucket64
FROM rb20_v2_5.h_members hm
JOIN rb20_v2_5.source_members sm
  ON sm.run_id = hm.run_id
 AND sm.ip_long = hm.ip_long;

DROP VIEW IF EXISTS rb20_v2_5.e_members_wide;
CREATE VIEW rb20_v2_5.e_members_wide AS
SELECT
  em.run_id,
  em.contract_version,
  em.shard_id,
  em.ip_long,
  em.atom27_id,
  em.e_run_id,

  sm.ip_address,
  sm."IP归属国家",
  sm."IP归属运营商",
  sm."过滤前上报次数",
  sm."上报次数",
  sm."过滤前设备数量",
  sm."设备数量",
  sm."应用数量",
  sm."活跃天数",
  sm."安卓ID数量",
  sm."OAID数量",
  sm."谷歌ID数量",
  sm."启动ID数量",
  sm."型号数量",
  sm."制造商数量",
  sm."深夜上报次数",
  sm."工作时上报次数",
  sm."工作日上报次数",
  sm."周末上报次数",
  sm."以太网接口上报次数",
  sm."代理上报次数",
  sm."Root设备上报次数",
  sm."ADB调试上报次数",
  sm."充电状态上报次数",
  sm."单设备最大上报次数",
  sm."DAA业务上报次数",
  sm."DNA业务上报次数",
  sm."WiFi可比上报次数",
  sm."SSID去重数",
  sm."BSSID去重数",
  sm."网关存在上报次数",
  sm."平均每设备上报次数",
  sm."周活跃天数比例",
  sm."深夜活动比例",
  sm."工作日周末平均比例",
  sm."平均每设备重启次数",
  sm."平均每设备应用数",
  sm."DAA DNA业务比例",
  sm."上报应用比例",
  sm."低安卓API设备比例",
  sm."WiFi设备数量",
  sm."WiFi设备比例",
  sm."移动网络设备数量",
  sm."移动网络设备比例",
  sm."VPN设备数量",
  sm."VPN设备比例",
  sm."空网络状态设备数量",
  sm."空网络状态设备比例",
  sm."异常网络设备数量",
  sm."异常网络设备比例",
  sm."有线网络设备数量",
  sm."有线网络设备比例",
  sm."SIM不可用比例",
  sm."无效总流量设备比例",
  sm."零移动流量设备比例",
  sm."制造商分布风险状态",
  sm."SDK版本分布异常分数",
  sm."开始日期",
  sm."结束日期",
  sm."创建时间",
  sm."活跃日期列表",
  sm."IP稳定性",

  sm.is_abnormal,
  sm.is_valid,
  sm.bucket64
FROM rb20_v2_5.e_members em
JOIN rb20_v2_5.source_members sm
  ON sm.run_id = em.run_id
 AND sm.shard_id = em.shard_id
 AND sm.ip_long = em.ip_long;

DROP VIEW IF EXISTS rb20_v2_5.f_members_wide;
CREATE VIEW rb20_v2_5.f_members_wide AS
SELECT
  fm.run_id,
  fm.contract_version,
  fm.shard_id,
  fm.ip_long,
  fm.atom27_id,

  sm.ip_address,
  sm."IP归属国家",
  sm."IP归属运营商",
  sm."过滤前上报次数",
  sm."上报次数",
  sm."过滤前设备数量",
  sm."设备数量",
  sm."应用数量",
  sm."活跃天数",
  sm."安卓ID数量",
  sm."OAID数量",
  sm."谷歌ID数量",
  sm."启动ID数量",
  sm."型号数量",
  sm."制造商数量",
  sm."深夜上报次数",
  sm."工作时上报次数",
  sm."工作日上报次数",
  sm."周末上报次数",
  sm."以太网接口上报次数",
  sm."代理上报次数",
  sm."Root设备上报次数",
  sm."ADB调试上报次数",
  sm."充电状态上报次数",
  sm."单设备最大上报次数",
  sm."DAA业务上报次数",
  sm."DNA业务上报次数",
  sm."WiFi可比上报次数",
  sm."SSID去重数",
  sm."BSSID去重数",
  sm."网关存在上报次数",
  sm."平均每设备上报次数",
  sm."周活跃天数比例",
  sm."深夜活动比例",
  sm."工作日周末平均比例",
  sm."平均每设备重启次数",
  sm."平均每设备应用数",
  sm."DAA DNA业务比例",
  sm."上报应用比例",
  sm."低安卓API设备比例",
  sm."WiFi设备数量",
  sm."WiFi设备比例",
  sm."移动网络设备数量",
  sm."移动网络设备比例",
  sm."VPN设备数量",
  sm."VPN设备比例",
  sm."空网络状态设备数量",
  sm."空网络状态设备比例",
  sm."异常网络设备数量",
  sm."异常网络设备比例",
  sm."有线网络设备数量",
  sm."有线网络设备比例",
  sm."SIM不可用比例",
  sm."无效总流量设备比例",
  sm."零移动流量设备比例",
  sm."制造商分布风险状态",
  sm."SDK版本分布异常分数",
  sm."开始日期",
  sm."结束日期",
  sm."创建时间",
  sm."活跃日期列表",
  sm."IP稳定性",

  sm.is_abnormal,
  sm.is_valid,
  sm.bucket64
FROM rb20_v2_5.f_members fm
JOIN rb20_v2_5.source_members sm
  ON sm.run_id = fm.run_id
 AND sm.shard_id = fm.shard_id
 AND sm.ip_long = fm.ip_long;
